"""Notification emails to Mihir."""
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict
from datetime import datetime
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

from .config import config

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"


class Notifier:
    """Sends notification emails to Mihir."""

    def __init__(self):
        self.jinja_env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
        self.to_email = config.profile.get('email')

    def send_new_roles_alert(self, roles: List[Dict]):
        """Send email alert about new job postings."""
        if not roles:
            return

        logger.info(f"Sending new roles alert for {len(roles)} jobs")

        # Group by company
        by_company = {}
        for role in roles:
            company = role['company']
            if company not in by_company:
                by_company[company] = []
            by_company[company].append(role)

        # Build email body
        body = f"Found {len(roles)} new matching job postings:\n\n"

        for company, company_roles in sorted(by_company.items()):
            body += f"## {company} ({len(company_roles)} roles)\n\n"
            for role in company_roles:
                body += f"- **{role['title']}**\n"
                if role.get('location'):
                    body += f"  Location: {role['location']}\n"
                body += f"  {role['url']}\n\n"

        body += f"\n---\nGenerated by Job Outreach Automation\n{datetime.now().strftime('%Y-%m-%d %H:%M')}"

        subject = f"🎯 {len(roles)} New Job Postings Found"

        self._send_notification(subject, body)

    def send_outreach_summary(self, stats: Dict):
        """Send daily outreach summary."""
        subject = "📊 Daily Outreach Summary"
        body = f"""Outreach Summary for {datetime.now().strftime('%Y-%m-%d')}

Emails sent: {stats.get('sent', 0)}
Failed: {stats.get('failed', 0)}
Skipped: {stats.get('skipped', 0)}

---
Generated by Job Outreach Automation
"""
        self._send_notification(subject, body)

    def send_draft_review_request(self, drafts: List[Dict]):
        """Send notification about pending drafts needing review."""
        if not drafts:
            return

        subject = f"📝 {len(drafts)} Email Drafts Awaiting Review"
        body = f"You have {len(drafts)} LLM-generated email drafts pending review:\n\n"

        for draft in drafts:
            body += f"- {draft.get('Contact Name')} at {draft.get('Company')}"
            if draft.get('Role Referenced'):
                body += f" (re: {draft.get('Role Referenced')})"
            body += "\n"

        body += f"\nTo review:\n  python -m src.main outreach --review-drafts\n"
        body += f"To approve all:\n  python -m src.main outreach --approve-all\n"
        body += f"To send approved:\n  python -m src.main outreach --send-approved\n"
        body += f"\n---\nGenerated by Job Outreach Automation\n{datetime.now().strftime('%Y-%m-%d %H:%M')}"

        self._send_notification(subject, body)

    def send_status_digest(self, stats: Dict):
        """Send daily status digest email."""
        subject = f"Job Search Status — {datetime.now().strftime('%Y-%m-%d')}"
        body = f"""Daily Status Digest

Companies tracked:    {stats.get('companies_tracked', 0)}
New roles (unread):   {stats.get('new_roles', 0)}
Pending email drafts: {stats.get('pending_drafts', 0)}

---
Generated by Job Outreach Automation
{datetime.now().strftime('%Y-%m-%d %H:%M')}
"""
        self._send_notification(subject, body)

    def send_error_alert(self, error_message: str):
        """Send error notification."""
        subject = "⚠️ Job Automation Error"
        body = f"""An error occurred in the job search automation:

{error_message}

---
Generated by Job Outreach Automation
{datetime.now().strftime('%Y-%m-%d %H:%M')}
"""
        self._send_notification(subject, body)

    def _send_notification(self, subject: str, body: str):
        """Send a notification email."""
        smtp_config = config.smtp

        if not smtp_config.get('user') or not smtp_config.get('password'):
            logger.warning("SMTP not configured - cannot send notification")
            return

        try:
            msg = MIMEMultipart()
            msg['From'] = f"Job Automation <{smtp_config['user']}>"
            msg['To'] = self.to_email
            msg['Subject'] = subject
            msg.attach(MIMEText(body, 'plain'))

            server = smtplib.SMTP(smtp_config['server'], smtp_config['port'])
            server.starttls()
            server.login(smtp_config['user'], smtp_config['password'])
            server.send_message(msg)
            server.quit()

            logger.info(f"Sent notification: {subject}")

        except Exception as e:
            logger.error(f"Failed to send notification: {e}")


# Global instance
notifier = Notifier()
