"""Notification emails to Mihir."""
import logging
import smtplib
from collections import defaultdict
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict
from datetime import datetime
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

from .config import config

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

# Tier ordering for the digest
TIER_ORDER = [
    "Tier 1 - Dream",
    "Tier 2 - Strong",
    "Tier 3 - Backup",
]

# CSS class mapping for tiers
TIER_CSS = {
    "Tier 1 - Dream": "tier1",
    "Tier 2 - Strong": "tier2",
    "Tier 3 - Backup": "tier3",
}


class Notifier:
    """Sends notification emails to Mihir."""

    def __init__(self):
        self.jinja_env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
        self.to_email = config.profile.get('email')

    def send_new_roles_digest(self, roles: List[Dict], company_tiers: Dict[str, str] = None):
        """Send HTML digest email about new job postings, grouped by tier then company.

        Args:
            roles: List of job dicts with company, title, location, url.
            company_tiers: Dict mapping company name -> tier string.
                          If None, all roles grouped under "Other".
        """
        if not roles:
            return

        if company_tiers is None:
            company_tiers = {}

        logger.info(f"Sending digest for {len(roles)} new roles")

        # Group roles: tier -> company -> [roles]
        tier_groups: Dict[str, Dict[str, List[Dict]]] = defaultdict(lambda: defaultdict(list))

        for role in roles:
            company = role.get('company', 'Unknown')
            tier = company_tiers.get(company, 'Tier 3 - Backup')
            tier_groups[tier][company].append(role)

        # Build ordered tier data for template
        tiers_data = []
        for tier_name in TIER_ORDER:
            if tier_name in tier_groups:
                companies = sorted(tier_groups[tier_name].items())
                tiers_data.append((tier_name, companies))

        # Any tiers not in TIER_ORDER (shouldn't happen, but be safe)
        for tier_name in tier_groups:
            if tier_name not in TIER_ORDER:
                companies = sorted(tier_groups[tier_name].items())
                tiers_data.append((tier_name, companies))

        # Count unique companies
        all_companies = set(role.get('company', '') for role in roles)

        # Render HTML
        template = self.jinja_env.get_template('digest.html')
        html_body = template.render(
            total_roles=len(roles),
            total_companies=len(all_companies),
            date=datetime.now().strftime('%b %d, %Y'),
            tiers=tiers_data,
        )

        subject = f"{len(roles)} New Job Postings — {datetime.now().strftime('%b %d')}"
        self._send_notification(subject, html_body, html=True)

    def send_outreach_summary(self, stats: Dict):
        """Send daily outreach summary."""
        subject = "Outreach Summary"
        body = f"""Outreach Summary for {datetime.now().strftime('%Y-%m-%d')}

Emails sent: {stats.get('sent', 0)}
Failed: {stats.get('failed', 0)}
Skipped: {stats.get('skipped', 0)}

---
Generated by Job Outreach Automation
"""
        self._send_notification(subject, body)

    def send_status_digest(self, stats: Dict):
        """Send daily status digest email."""
        subject = f"Job Search Status — {datetime.now().strftime('%Y-%m-%d')}"
        body = f"""Daily Status Digest

Companies tracked:    {stats.get('companies_tracked', 0)}
New roles (unread):   {stats.get('new_roles', 0)}

---
Generated by Job Outreach Automation
{datetime.now().strftime('%Y-%m-%d %H:%M')}
"""
        self._send_notification(subject, body)

    def send_error_alert(self, error_message: str):
        """Send error notification."""
        subject = "Job Automation Error"
        body = f"""An error occurred in the job search automation:

{error_message}

---
Generated by Job Outreach Automation
{datetime.now().strftime('%Y-%m-%d %H:%M')}
"""
        self._send_notification(subject, body)

    def _send_notification(self, subject: str, body: str, html: bool = False):
        """Send a notification email."""
        smtp_config = config.smtp

        if not smtp_config.get('user') or not smtp_config.get('password'):
            logger.warning("SMTP not configured - cannot send notification")
            return

        try:
            msg = MIMEMultipart()
            msg['From'] = f"Job Automation <{smtp_config['user']}>"
            msg['To'] = self.to_email
            msg['Subject'] = subject

            content_type = 'html' if html else 'plain'
            msg.attach(MIMEText(body, content_type))

            server = smtplib.SMTP(smtp_config['server'], smtp_config['port'])
            server.starttls()
            server.login(smtp_config['user'], smtp_config['password'])
            server.send_message(msg)
            server.quit()

            logger.info(f"Sent notification: {subject}")

        except Exception as e:
            logger.error(f"Failed to send notification: {e}")


# Global instance
notifier = Notifier()
